x-db-env: &db_env
  POSTGRES_DB: $PSQL_NAME
  POSTGRES_USER: $PSQL_USER
  POSTGRES_PASSWORD: $PSQL_PASS

x-backend-env: &backend_env
   <<: *db_env
   DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
   DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
   DJANGO_DEBUG: $DJANGO_DEBUG
   POSTGRES_HOST: postgres_db
   POSTGRES_PORT: $PSQL_PORT

x-bot-env: &bot_env
  BOT_TOKEN: $BOT_TOKEN
  BASE_API_URL: $BASE_API_URL
  BOT_API_AUTH_TOKEN: $BOT_API_AUTH_TOKEN

x-celery-env: &celery_env
  CELERY_BROKER_URL: $CELERY_BROKER_URL
  CELERY_RESULT_BACKEND: $CELERY_RESULT_BACKEND

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ["sh", "-c", "python manage.py migrate && python manage.py collectstatic && uvicorn todo_list.asgi:application --host 0.0.0.0 --port 8000"]
    depends_on:
      - postgres_db
      - redis
    environment:
      <<: [*backend_env, *celery_env]
    ports:
      - "8000:8000"

  postgres_db:
    restart: always
    image: postgres:16
    environment:
      <<: *db_env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    restart: always
    entrypoint: ["sh", "-c", "python main.py"]
    build:
      context: ./bot
      dockerfile: Dockerfile
    environment:
      <<: *bot_env
    depends_on:
      - backend

  bot_celery_worker:
    restart: always
    build:
      context: ./bot
      dockerfile: Dockerfile
    entrypoint: ["sh", "-c", "celery -A celery_worker.app worker --loglevel=info --concurrency 1 -E"]
    depends_on:
      - backend
    environment:
      <<: [*bot_env, *celery_env]

  redis:
    restart: always
    image: eqalpha/keydb

volumes:
  postgres_data: